// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Metric struct {
	Name         string `json:"name"`
	HighTreshold int    `json:"highTreshold"`
	LowTreshold  int    `json:"lowTreshold"`
	Current      int    `json:"current"`
	UserID       string `json:"userId"`
}

type Service struct {
	UserID  string    `json:"userID"`
	Name    string    `json:"name"`
	Region  string    `json:"region"`
	Metrics []*Metric `json:"metrics"`
}
